### ISSUE TITLE
There are no changes to the rating of items in the reward system

### ISSUE THREAD

**Issue by atlantiswqq** [Azure-Samples/cognitive-services-quickstart-code#261] opened 2021-06-24 09:52 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report 

```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> mac os

### Versions
> python3.6

### Mention any other details that might be useful
When I used the Personalizer service, I found that giving a reward a 0 had no effect on the recommended result
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by fsharpn00b** [comment] 2021-06-25 00:15
Hello atlantiswqq,

Thank you for letting us know about this. I will try to reproduce it. Can you post or link to the code you are running that is giving you this result? That will help us see what might be causing it.

Thank you,
fsharpn00b

**Comment by fsharpn00b** [comment] 2021-07-11 15:09
Hello atlantiswqq,

I am closing this issue for now as I am unable to reproduce it, but please feel free to reopen it.
Thank you and best regards,
fsharpn00b

**Closed by fsharpn00b** 2021-07-11 15:09 UTC
