### ISSUE TITLE
CRITICAL lines of code are DUPLICATED !!! 

### ISSUE THREAD

**Issue by markvogt** [Azure-Samples/cognitive-services-quickstart-code#183] opened 2020-11-20 01:37 UTC
OBSERVED: 
Lines 18 & 19 are IDENTICAL to Lines 27 & 28   <--- WHY DOES MICROSOFT PUBLISH CODE IT HAS NEVER IN FACT TESTED ????
HOW can SO MANY YEARS GO BY with NO ONE FIXING SUCH BLUNDERS ???

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by v-jaswel** [comment] 2020-11-20 03:26
Hello @markvogt,

Can you tell me which file you are referring to?

Thank you,
v-jaswel

**Comment by v-jaswel** [comment] 2020-11-24 20:28
Hello @markvogt,

I am going to close this issue for now as I cannot address the issue without knowing which file is affected, but please feel free to reopen it.

Thank you,
v-jaswel

**Closed by v-jaswel** 2020-11-24 20:28 UTC

**Comment by AgribotGit** [comment] 2021-03-16 15:28
the reported defect still exists.
here it is;-


The iteration is now trained. Publish it to the project endpoint
trainer.publish_iteration(project.id, iteration.id, publish_iteration_name, prediction_resource_id)
print ("Done!")
</snippet_train>

THIS IS A DUPLICATE OF THE ABOVE LINES AND CAUSES AN ERROR
<snippet_publish>
The iteration is now trained. Publish it to the project endpoint
trainer.publish_iteration(project.id, iteration.id, publish_iteration_name, prediction_resource_id) 
print ("Done!")
</snippet_publish>

Also ... there is some problem ( cause unknown ) with the line ;-

project.id, publish_iteration_name, image_contents.read())

The above line does NOT work. It causes ... Invalid iteration  error !!

Please correct the code and please notify me how to resolve the above invalid iteration defect

thanks
